// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/matchmaker/users": {
            "post": {
                "description": "Handles request to add a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matching"
                ],
                "summary": "Adding a user.",
                "parameters": [
                    {
                        "description": "Player",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created Player",
                        "schema": {
                            "$ref": "#/definitions/models.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddRequest": {
            "type": "object",
            "properties": {
                "latency": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "skill": {
                    "type": "number"
                }
            }
        },
        "models.Player": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "latency": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "skill": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "localhost:8900",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Matchmaker API",
	Description:      "This is matchmaker server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
