definitions:
  models.AddRequest:
    properties:
      latency:
        type: number
      name:
        type: string
      skill:
        type: number
    type: object
  models.Player:
    properties:
      added:
        type: string
      id:
        type: integer
      latency:
        type: number
      name:
        type: string
      skill:
        type: number
    type: object
host: localhost:8900
info:
  contact: {}
  description: This is matchmaker server.
  title: Matchmaker API
paths:
  /matchmaker/users:
    post:
      consumes:
      - application/json
      description: Handles request to add a new user
      parameters:
      - description: Player
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Created Player
          schema:
            $ref: '#/definitions/models.Player'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Adding a user.
      tags:
      - matching
swagger: "2.0"
